- type: coffee_table
  initial_pose: [3.345, 2.99, 1.5708]
  markers:
    - id: 1
      x: -0.57
      y: 0.2125
      theta: 0.0
    - id: 2
      x: 0.57
      y: -0.2125
      theta: 0.0
- type: kitchen_table
  initial_pose: [3.877, 5.704, 1.5708]
  markers:
    - id: 3
      x: -0.41
      y: 0.4025
      theta: 0.0
    - id: 4
      x: 0.41
      y: -0.4025
      theta: 0.0
- type: kitchen_chair
  initial_pose: [3.345, 5.775, -1.5708]
  markers:
    - id: 5
      x: -0.1525
      y: 0.16
      theta: 0.0
    - id: 6
      x: 0.14
      y: -0.10
      theta: 0.0
- type: large_chair
  initial_pose: [3.643, 1.1, 0.0]
  markers:
    - id: 7
      x: -0.195
      y: 0.1825
      theta: 0.0
    - id: 8
      x: 0.195
      y: -0.1825
      theta: 0.0
- type: large_chair
  initial_pose: [2.62, 1.1, 0.0]
  markers:
    - id: 9
      x: -0.195
      y: 0.1825
      theta: 0.0
    - id: 10
      x: 0.195
      y: -0.1825
      theta: 0.0
- type: sofa
  initial_pose: [4.497, 2.94, 1.5708]
  markers:
    - id: 12
      x: -0.35
      y: 0.215
      theta: 0.0
    - id: 11
      x: 0.35
      y: -0.215
      theta: 0.0